<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Dell-5577-Sidhu" failures="1" tests="2" name="Guest_Module" time="50.476" errors="0" timestamp="2023-10-23T12:46:43 EDT">
  <testcase classname="test_layer.Guest_Test" name="Guest_TC1_Navigate_Products" time="8.793"/>
  <testcase classname="test_layer.Guest_Test" name="Guest_TC2_Buy_Product" time="30.448">
    <failure type="java.lang.AssertionError" message="expected [Checkout (1 item)] but found [Sign-in to checkout]">
      <![CDATA[java.lang.AssertionError: expected [Checkout (1 item)] but found [Sign-in to checkout]
at test_layer.Guest_Test.Guest_TC2_Buy_Product(Guest_Test.java:47)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Guest_TC2_Buy_Product -->
</testsuite> <!-- Guest_Module -->
